# Generated by Django 6.0.1 on 2026-04-15 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', '新規'), ('contacted', '連絡済み'), ('proposed', '提案中'), ('won', '獲得'), ('lost', 'お断り'), ('on_hold', '保留'), ('needs_follow_up', '要フォロー')], default='new', max_length=20)),
                ('deal_name', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', '電話'), ('email', 'メール'), ('meeting', 'ミーティング')], max_length=20)),
                ('date', models.DateField()),
                ('memo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.deal')),
            ],
        ),
    ]
